settings:
  #Prefix that will be adding to every message sending by this plugin
  prefix: '&2RPS &7⋙ '

  gameConfig:
    active: true
    #Maximum amount of bet (0 = no limit)
    maxBet: 500000
    #Minimum amount of bet
    minBet: 0
    #in seconds
    acceptTime: 30
    #czas liczy się od momętu aż ktoś wybieze
    chooseTime: 30
    replayOnDraw: true
    #nie wybranie w określonym czasie = leave
    loseBetOnLeave: true

  gui:
    main:
      title: "Chuj"
      rock:
        item: COBBLESTONE
        name: "&7&lRock"
      paper:
        item: PAPER
        name: "&f&lPaper"
      scissors:
        item: SHEARS
        name: "&c&lScissors"
      fillItem:
        item: GRAY_STAINED_GLASS_PANE
        name: " "

  messages:
    noPermission: '&cYou do not have permission to use this command'
    badUseRpsGameCmd: '&7You have to give player name and bet argument &f/&7rps game &f<&7player&f> <&7bet&f>'
    badUseRpsAcceptCmd: '&7You have to give player name argument &f/&7rps accept &f<&7player&f>'
    myselfInvite: '&7You cannot invite yourself'
    #Dodac placeholder $ akceptowanie po kliknęciu na czat
    rpsInvite: '&aPlayer &f{NAME}&a invites you to play &7rock-paper-scissors&a for &f{BET}&a$. To accept use command &f/&7rps accept &f<&7player&f>'
    notEnoughMoney: '&7You or your rival dose have enough money for this game'
    playerNotExist: '&7Player with name &f{NAME}&7 is not online or does not exist'
    noInvitation: '&7You do not have invitation form player &f{NAME}'
    winMessage: 'wygrałes'
    loseMessage: 'przergrana'
    drawMessage: "remis"


