name: RockPaperScissors
version: '1.1.1'
main: pl.pavetti.rockpaperscissors.Main
authors: [ 'Rigoletto' ]
description: Rock Paper Scissors game
api-version: '1.20'
softdepend: ['Vault']
commands:
  rps:
  rpsreload:
    permission: rps.admin
