name: RockPaperScissors
version: '1.2.3'
main: pl.pavetti.rockpaperscissors.Main
authors: [ 'Rigoletto' ]
description: Rock Paper Scissors game
api-version: '1.16'
softdepend: ['Vault']
commands:
  rps:
  rpsreload:
    permission: rps.admin
  rpstest: